const DISCORD_TOKEN='YOUR_DISCORD_TOKEN_HERE',
    TWITCH_CLIENT_ID='YOUR_TWITCH_CLIENT_ID_HERE',
    TWITCH_API_ENDPOINT='https://api.twitch.tv/kraken/streams?channel=';


module.exports = {
    DISCORD_TOKEN: DISCORD_TOKEN,
    TWITCH_CLIENT_ID: TWITCH_CLIENT_ID,
    TWITCH_API_ENDPOINT: TWITCH_API_ENDPOINT
};